# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsgit < Formula
  desc "ls for git repositories — list subdirs with branch and status"
  homepage "https://github.com/itinance/lsgit"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itinance/lsgit/releases/download/v0.2.0/lsgit_darwin_amd64.tar.gz"
      sha256 "a6ae90cf7b10e5c20d8ece6c03a8725356be96f3d40b59fab58f03c53c6880db"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itinance/lsgit/releases/download/v0.2.0/lsgit_darwin_arm64.tar.gz"
      sha256 "3a4a5214312cb2ec25523a99331c09d77280ec9d35fa8429499bddffe1e5c0d9"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.2.0/lsgit_linux_amd64.tar.gz"
      sha256 "862a057deb3b7153b7bcef969dfcb4de5345659620edb89c7e5d327f3365cccb"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.2.0/lsgit_linux_arm64.tar.gz"
      sha256 "eb44d5098a9a90f6deacde941df42123bb07a66f7da6cf182a960ba4390532fb"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  test do
    system "#{bin}/lsgit --version"
  end
end
