# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsgit < Formula
  desc "ls for git repositories — list subdirs with branch and status"
  homepage "https://github.com/itinance/lsgit"
  version "0.3.0-2-gf985134"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0-2-gf985134/lsgit_darwin_amd64.tar.gz"
      sha256 "bba73e98989acc45ab55c1f8d1f14e10f53ce27031170c0558957da0921a6baf"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0-2-gf985134/lsgit_darwin_arm64.tar.gz"
      sha256 "1a57bc5939b6992b76934ecb89a2d9e5ade8a4e6e779dd01953bdc72e1bfc3c2"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0-2-gf985134/lsgit_linux_amd64.tar.gz"
      sha256 "4712dd361d7093fd4add48cc541643d2f177fe31a432565ba1daca034b822a43"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0-2-gf985134/lsgit_linux_arm64.tar.gz"
      sha256 "2887dfd29c55b603b4543f0bc9df9d92218c507628636e040e5741328d0f1574"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  test do
    system "#{bin}/lsgit --version"
  end
end
