# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lsgit < Formula
  desc "ls for git repositories — list subdirs with branch and status"
  homepage "https://github.com/itinance/lsgit"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0/lsgit_darwin_amd64.tar.gz"
      sha256 "6841c7a7dbb39f7e31b55d6539111c82ffe2e46edf7ef25547bfafd9dd1d2834"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0/lsgit_darwin_arm64.tar.gz"
      sha256 "aac43dcf65a65b7306bd446d6290ffb9b887c15002e4c637b8327ef828f28250"

      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0/lsgit_linux_amd64.tar.gz"
      sha256 "9a10e73bf4d23fe021165317aeb91016dbd4f99abbe5278b3792d051f1299aa3"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/itinance/lsgit/releases/download/v0.3.0/lsgit_linux_arm64.tar.gz"
      sha256 "fa1074e7118a720358294b4ea30edb74306950524489f392479284dec9cea61f"
      define_method(:install) do
        bin.install "lsgit"
      end
    end
  end

  test do
    system "#{bin}/lsgit --version"
  end
end
